/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.science.service.persistence.RequiredLibConfirmPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RequiredLibConfirm service. Represents a row in the &quot;EDAPP_RequiredLibConfirm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.RequiredLibConfirmModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.RequiredLibConfirmImpl}.
 * </p>
 *
 * @author EDISON
 * @see RequiredLibConfirm
 * @see org.kisti.edison.science.model.impl.RequiredLibConfirmImpl
 * @see org.kisti.edison.science.model.impl.RequiredLibConfirmModelImpl
 * @generated
 */
public interface RequiredLibConfirmModel extends BaseModel<RequiredLibConfirm> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a required lib confirm model instance should use the {@link RequiredLibConfirm} interface instead.
	 */

	/**
	 * Returns the primary key of this required lib confirm.
	 *
	 * @return the primary key of this required lib confirm
	 */
	public RequiredLibConfirmPK getPrimaryKey();

	/**
	 * Sets the primary key of this required lib confirm.
	 *
	 * @param primaryKey the primary key of this required lib confirm
	 */
	public void setPrimaryKey(RequiredLibConfirmPK primaryKey);

	/**
	 * Returns the required lib ID of this required lib confirm.
	 *
	 * @return the required lib ID of this required lib confirm
	 */
	public long getRequiredLibId();

	/**
	 * Sets the required lib ID of this required lib confirm.
	 *
	 * @param requiredLibId the required lib ID of this required lib confirm
	 */
	public void setRequiredLibId(long requiredLibId);

	/**
	 * Returns the science app ID of this required lib confirm.
	 *
	 * @return the science app ID of this required lib confirm
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this required lib confirm.
	 *
	 * @param scienceAppId the science app ID of this required lib confirm
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the company ID of this required lib confirm.
	 *
	 * @return the company ID of this required lib confirm
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this required lib confirm.
	 *
	 * @param companyId the company ID of this required lib confirm
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this required lib confirm.
	 *
	 * @return the user ID of this required lib confirm
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this required lib confirm.
	 *
	 * @param userId the user ID of this required lib confirm
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this required lib confirm.
	 *
	 * @return the user uuid of this required lib confirm
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this required lib confirm.
	 *
	 * @param userUuid the user uuid of this required lib confirm
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the required date of this required lib confirm.
	 *
	 * @return the required date of this required lib confirm
	 */
	public Date getRequiredDate();

	/**
	 * Sets the required date of this required lib confirm.
	 *
	 * @param requiredDate the required date of this required lib confirm
	 */
	public void setRequiredDate(Date requiredDate);

	/**
	 * Returns the confirm date of this required lib confirm.
	 *
	 * @return the confirm date of this required lib confirm
	 */
	public Date getConfirmDate();

	/**
	 * Sets the confirm date of this required lib confirm.
	 *
	 * @param confirmDate the confirm date of this required lib confirm
	 */
	public void setConfirmDate(Date confirmDate);

	/**
	 * Returns the library name of this required lib confirm.
	 *
	 * @return the library name of this required lib confirm
	 */
	@AutoEscape
	public String getLibraryName();

	/**
	 * Sets the library name of this required lib confirm.
	 *
	 * @param libraryName the library name of this required lib confirm
	 */
	public void setLibraryName(String libraryName);

	/**
	 * Returns the library version of this required lib confirm.
	 *
	 * @return the library version of this required lib confirm
	 */
	@AutoEscape
	public String getLibraryVersion();

	/**
	 * Sets the library version of this required lib confirm.
	 *
	 * @param libraryVersion the library version of this required lib confirm
	 */
	public void setLibraryVersion(String libraryVersion);

	/**
	 * Returns the required content of this required lib confirm.
	 *
	 * @return the required content of this required lib confirm
	 */
	@AutoEscape
	public String getRequiredContent();

	/**
	 * Sets the required content of this required lib confirm.
	 *
	 * @param requiredContent the required content of this required lib confirm
	 */
	public void setRequiredContent(String requiredContent);

	/**
	 * Returns the required state of this required lib confirm.
	 *
	 * @return the required state of this required lib confirm
	 */
	@AutoEscape
	public String getRequiredState();

	/**
	 * Sets the required state of this required lib confirm.
	 *
	 * @param requiredState the required state of this required lib confirm
	 */
	public void setRequiredState(String requiredState);

	/**
	 * Returns the confirm content of this required lib confirm.
	 *
	 * @return the confirm content of this required lib confirm
	 */
	@AutoEscape
	public String getConfirmContent();

	/**
	 * Sets the confirm content of this required lib confirm.
	 *
	 * @param confirmContent the confirm content of this required lib confirm
	 */
	public void setConfirmContent(String confirmContent);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.science.model.RequiredLibConfirm requiredLibConfirm);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.RequiredLibConfirm> toCacheModel();

	@Override
	public org.kisti.edison.science.model.RequiredLibConfirm toEscapedModel();

	@Override
	public org.kisti.edison.science.model.RequiredLibConfirm toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}