/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RequiredLib service. Represents a row in the &quot;EDAPP_RequiredLib&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.RequiredLibModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.RequiredLibImpl}.
 * </p>
 *
 * @author EDISON
 * @see RequiredLib
 * @see org.kisti.edison.science.model.impl.RequiredLibImpl
 * @see org.kisti.edison.science.model.impl.RequiredLibModelImpl
 * @generated
 */
public interface RequiredLibModel extends BaseModel<RequiredLib> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a required lib model instance should use the {@link RequiredLib} interface instead.
	 */

	/**
	 * Returns the primary key of this required lib.
	 *
	 * @return the primary key of this required lib
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this required lib.
	 *
	 * @param primaryKey the primary key of this required lib
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the required lib ID of this required lib.
	 *
	 * @return the required lib ID of this required lib
	 */
	public long getRequiredLibId();

	/**
	 * Sets the required lib ID of this required lib.
	 *
	 * @param requiredLibId the required lib ID of this required lib
	 */
	public void setRequiredLibId(long requiredLibId);

	/**
	 * Returns the group ID of this required lib.
	 *
	 * @return the group ID of this required lib
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this required lib.
	 *
	 * @param groupId the group ID of this required lib
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this required lib.
	 *
	 * @return the company ID of this required lib
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this required lib.
	 *
	 * @param companyId the company ID of this required lib
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this required lib.
	 *
	 * @return the user ID of this required lib
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this required lib.
	 *
	 * @param userId the user ID of this required lib
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this required lib.
	 *
	 * @return the user uuid of this required lib
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this required lib.
	 *
	 * @param userUuid the user uuid of this required lib
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this required lib.
	 *
	 * @return the create date of this required lib
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this required lib.
	 *
	 * @param createDate the create date of this required lib
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this required lib.
	 *
	 * @return the modified date of this required lib
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this required lib.
	 *
	 * @param modifiedDate the modified date of this required lib
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the library name of this required lib.
	 *
	 * @return the library name of this required lib
	 */
	@AutoEscape
	public String getLibraryName();

	/**
	 * Sets the library name of this required lib.
	 *
	 * @param libraryName the library name of this required lib
	 */
	public void setLibraryName(String libraryName);

	/**
	 * Returns the library version of this required lib.
	 *
	 * @return the library version of this required lib
	 */
	@AutoEscape
	public String getLibraryVersion();

	/**
	 * Sets the library version of this required lib.
	 *
	 * @param libraryVersion the library version of this required lib
	 */
	public void setLibraryVersion(String libraryVersion);

	/**
	 * Returns the library type of this required lib.
	 *
	 * @return the library type of this required lib
	 */
	@AutoEscape
	public String getLibraryType();

	/**
	 * Sets the library type of this required lib.
	 *
	 * @param libraryType the library type of this required lib
	 */
	public void setLibraryType(String libraryType);

	/**
	 * Returns the library src path of this required lib.
	 *
	 * @return the library src path of this required lib
	 */
	@AutoEscape
	public String getLibrarySrcPath();

	/**
	 * Sets the library src path of this required lib.
	 *
	 * @param librarySrcPath the library src path of this required lib
	 */
	public void setLibrarySrcPath(String librarySrcPath);

	/**
	 * Returns the install script of this required lib.
	 *
	 * @return the install script of this required lib
	 */
	@AutoEscape
	public String getInstallScript();

	/**
	 * Sets the install script of this required lib.
	 *
	 * @param installScript the install script of this required lib
	 */
	public void setInstallScript(String installScript);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.science.model.RequiredLib requiredLib);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.RequiredLib> toCacheModel();

	@Override
	public org.kisti.edison.science.model.RequiredLib toEscapedModel();

	@Override
	public org.kisti.edison.science.model.RequiredLib toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}