/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RequiredModule service. Represents a row in the &quot;EDAPP_RequiredModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.RequiredModuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.RequiredModuleImpl}.
 * </p>
 *
 * @author EDISON
 * @see RequiredModule
 * @see org.kisti.edison.science.model.impl.RequiredModuleImpl
 * @see org.kisti.edison.science.model.impl.RequiredModuleModelImpl
 * @generated
 */
public interface RequiredModuleModel extends BaseModel<RequiredModule> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a required module model instance should use the {@link RequiredModule} interface instead.
	 */

	/**
	 * Returns the primary key of this required module.
	 *
	 * @return the primary key of this required module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this required module.
	 *
	 * @param primaryKey the primary key of this required module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the required module ID of this required module.
	 *
	 * @return the required module ID of this required module
	 */
	public long getRequiredModuleId();

	/**
	 * Sets the required module ID of this required module.
	 *
	 * @param requiredModuleId the required module ID of this required module
	 */
	public void setRequiredModuleId(long requiredModuleId);

	/**
	 * Returns the group ID of this required module.
	 *
	 * @return the group ID of this required module
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this required module.
	 *
	 * @param groupId the group ID of this required module
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this required module.
	 *
	 * @return the company ID of this required module
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this required module.
	 *
	 * @param companyId the company ID of this required module
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this required module.
	 *
	 * @return the user ID of this required module
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this required module.
	 *
	 * @param userId the user ID of this required module
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this required module.
	 *
	 * @return the user uuid of this required module
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this required module.
	 *
	 * @param userUuid the user uuid of this required module
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this required module.
	 *
	 * @return the create date of this required module
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this required module.
	 *
	 * @param createDate the create date of this required module
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this required module.
	 *
	 * @return the modified date of this required module
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this required module.
	 *
	 * @param modifiedDate the modified date of this required module
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the module name of this required module.
	 *
	 * @return the module name of this required module
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this required module.
	 *
	 * @param moduleName the module name of this required module
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the module version of this required module.
	 *
	 * @return the module version of this required module
	 */
	@AutoEscape
	public String getModuleVersion();

	/**
	 * Sets the module version of this required module.
	 *
	 * @param moduleVersion the module version of this required module
	 */
	public void setModuleVersion(String moduleVersion);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.science.model.RequiredModule requiredModule);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.RequiredModule> toCacheModel();

	@Override
	public org.kisti.edison.science.model.RequiredModule toEscapedModel();

	@Override
	public org.kisti.edison.science.model.RequiredModule toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}