/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.science.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.science.service.persistence.ScienceAppFavoritePK;

import java.io.Serializable;

/**
 * The base model interface for the ScienceAppFavorite service. Represents a row in the &quot;EDAPP_ScienceAppFavorite&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.science.model.impl.ScienceAppFavoriteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.science.model.impl.ScienceAppFavoriteImpl}.
 * </p>
 *
 * @author EDISON
 * @see ScienceAppFavorite
 * @see org.kisti.edison.science.model.impl.ScienceAppFavoriteImpl
 * @see org.kisti.edison.science.model.impl.ScienceAppFavoriteModelImpl
 * @generated
 */
public interface ScienceAppFavoriteModel extends BaseModel<ScienceAppFavorite> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app favorite model instance should use the {@link ScienceAppFavorite} interface instead.
	 */

	/**
	 * Returns the primary key of this science app favorite.
	 *
	 * @return the primary key of this science app favorite
	 */
	public ScienceAppFavoritePK getPrimaryKey();

	/**
	 * Sets the primary key of this science app favorite.
	 *
	 * @param primaryKey the primary key of this science app favorite
	 */
	public void setPrimaryKey(ScienceAppFavoritePK primaryKey);

	/**
	 * Returns the science app ID of this science app favorite.
	 *
	 * @return the science app ID of this science app favorite
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app favorite.
	 *
	 * @param scienceAppId the science app ID of this science app favorite
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the user ID of this science app favorite.
	 *
	 * @return the user ID of this science app favorite
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this science app favorite.
	 *
	 * @param userId the user ID of this science app favorite
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this science app favorite.
	 *
	 * @return the user uuid of this science app favorite
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this science app favorite.
	 *
	 * @param userUuid the user uuid of this science app favorite
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this science app favorite.
	 *
	 * @return the group ID of this science app favorite
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this science app favorite.
	 *
	 * @param groupId the group ID of this science app favorite
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.science.model.ScienceAppFavorite scienceAppFavorite);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.science.model.ScienceAppFavorite> toCacheModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppFavorite toEscapedModel();

	@Override
	public org.kisti.edison.science.model.ScienceAppFavorite toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}