/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SendMailContent service. Represents a row in the &quot;EDMAIL_SendMailContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.SendMailContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.SendMailContentImpl}.
 * </p>
 *
 * @author EDISON
 * @see SendMailContent
 * @see org.kisti.edison.model.impl.SendMailContentImpl
 * @see org.kisti.edison.model.impl.SendMailContentModelImpl
 * @generated
 */
public interface SendMailContentModel extends BaseModel<SendMailContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a send mail content model instance should use the {@link SendMailContent} interface instead.
	 */

	/**
	 * Returns the primary key of this send mail content.
	 *
	 * @return the primary key of this send mail content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this send mail content.
	 *
	 * @param primaryKey the primary key of this send mail content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the send mail ID of this send mail content.
	 *
	 * @return the send mail ID of this send mail content
	 */
	public long getSendMailId();

	/**
	 * Sets the send mail ID of this send mail content.
	 *
	 * @param sendMailId the send mail ID of this send mail content
	 */
	public void setSendMailId(long sendMailId);

	/**
	 * Returns the user ID of this send mail content.
	 *
	 * @return the user ID of this send mail content
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this send mail content.
	 *
	 * @param userId the user ID of this send mail content
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this send mail content.
	 *
	 * @return the user uuid of this send mail content
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this send mail content.
	 *
	 * @param userUuid the user uuid of this send mail content
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the send count of this send mail content.
	 *
	 * @return the send count of this send mail content
	 */
	public int getSendCount();

	/**
	 * Sets the send count of this send mail content.
	 *
	 * @param sendCount the send count of this send mail content
	 */
	public void setSendCount(int sendCount);

	/**
	 * Returns the success count of this send mail content.
	 *
	 * @return the success count of this send mail content
	 */
	public int getSuccessCount();

	/**
	 * Sets the success count of this send mail content.
	 *
	 * @param successCount the success count of this send mail content
	 */
	public void setSuccessCount(int successCount);

	/**
	 * Returns the fail count of this send mail content.
	 *
	 * @return the fail count of this send mail content
	 */
	public int getFailCount();

	/**
	 * Sets the fail count of this send mail content.
	 *
	 * @param failCount the fail count of this send mail content
	 */
	public void setFailCount(int failCount);

	/**
	 * Returns the send date of this send mail content.
	 *
	 * @return the send date of this send mail content
	 */
	public Date getSendDate();

	/**
	 * Sets the send date of this send mail content.
	 *
	 * @param sendDate the send date of this send mail content
	 */
	public void setSendDate(Date sendDate);

	/**
	 * Returns the site group of this send mail content.
	 *
	 * @return the site group of this send mail content
	 */
	@AutoEscape
	public String getSiteGroup();

	/**
	 * Sets the site group of this send mail content.
	 *
	 * @param siteGroup the site group of this send mail content
	 */
	public void setSiteGroup(String siteGroup);

	/**
	 * Returns the user group of this send mail content.
	 *
	 * @return the user group of this send mail content
	 */
	@AutoEscape
	public String getUserGroup();

	/**
	 * Sets the user group of this send mail content.
	 *
	 * @param userGroup the user group of this send mail content
	 */
	public void setUserGroup(String userGroup);

	/**
	 * Returns the state of this send mail content.
	 *
	 * @return the state of this send mail content
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this send mail content.
	 *
	 * @param state the state of this send mail content
	 */
	public void setState(String state);

	/**
	 * Returns the title of this send mail content.
	 *
	 * @return the title of this send mail content
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this send mail content.
	 *
	 * @param title the title of this send mail content
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this send mail content.
	 *
	 * @return the content of this send mail content
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this send mail content.
	 *
	 * @param content the content of this send mail content
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.model.SendMailContent sendMailContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.SendMailContent> toCacheModel();

	@Override
	public org.kisti.edison.model.SendMailContent toEscapedModel();

	@Override
	public org.kisti.edison.model.SendMailContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}