/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the SimulationJobData service. Represents a row in the &quot;EDSIM_SimulationJobData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.bestsimulation.model.impl.SimulationJobDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.bestsimulation.model.impl.SimulationJobDataImpl}.
 * </p>
 *
 * @author EDISON
 * @see SimulationJobData
 * @see org.kisti.edison.bestsimulation.model.impl.SimulationJobDataImpl
 * @see org.kisti.edison.bestsimulation.model.impl.SimulationJobDataModelImpl
 * @generated
 */
public interface SimulationJobDataModel extends BaseModel<SimulationJobData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a simulation job data model instance should use the {@link SimulationJobData} interface instead.
	 */

	/**
	 * Returns the primary key of this simulation job data.
	 *
	 * @return the primary key of this simulation job data
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this simulation job data.
	 *
	 * @param primaryKey the primary key of this simulation job data
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the job uuid of this simulation job data.
	 *
	 * @return the job uuid of this simulation job data
	 */
	@AutoEscape
	public String getJobUuid();

	/**
	 * Sets the job uuid of this simulation job data.
	 *
	 * @param jobUuid the job uuid of this simulation job data
	 */
	public void setJobUuid(String jobUuid);

	/**
	 * Returns the job data of this simulation job data.
	 *
	 * @return the job data of this simulation job data
	 */
	public String getJobData();

	/**
	 * Returns the localized job data of this simulation job data in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized job data of this simulation job data
	 */
	@AutoEscape
	public String getJobData(Locale locale);

	/**
	 * Returns the localized job data of this simulation job data in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized job data of this simulation job data. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getJobData(Locale locale, boolean useDefault);

	/**
	 * Returns the localized job data of this simulation job data in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized job data of this simulation job data
	 */
	@AutoEscape
	public String getJobData(String languageId);

	/**
	 * Returns the localized job data of this simulation job data in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized job data of this simulation job data
	 */
	@AutoEscape
	public String getJobData(String languageId, boolean useDefault);

	@AutoEscape
	public String getJobDataCurrentLanguageId();

	@AutoEscape
	public String getJobDataCurrentValue();

	/**
	 * Returns a map of the locales and localized job datas of this simulation job data.
	 *
	 * @return the locales and localized job datas of this simulation job data
	 */
	public Map<Locale, String> getJobDataMap();

	/**
	 * Sets the job data of this simulation job data.
	 *
	 * @param jobData the job data of this simulation job data
	 */
	public void setJobData(String jobData);

	/**
	 * Sets the localized job data of this simulation job data in the language.
	 *
	 * @param jobData the localized job data of this simulation job data
	 * @param locale the locale of the language
	 */
	public void setJobData(String jobData, Locale locale);

	/**
	 * Sets the localized job data of this simulation job data in the language, and sets the default locale.
	 *
	 * @param jobData the localized job data of this simulation job data
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setJobData(String jobData, Locale locale, Locale defaultLocale);

	public void setJobDataCurrentLanguageId(String languageId);

	/**
	 * Sets the localized job datas of this simulation job data from the map of locales and localized job datas.
	 *
	 * @param jobDataMap the locales and localized job datas of this simulation job data
	 */
	public void setJobDataMap(Map<Locale, String> jobDataMap);

	/**
	 * Sets the localized job datas of this simulation job data from the map of locales and localized job datas, and sets the default locale.
	 *
	 * @param jobDataMap the locales and localized job datas of this simulation job data
	 * @param defaultLocale the default locale
	 */
	public void setJobDataMap(Map<Locale, String> jobDataMap,
		Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.bestsimulation.model.SimulationJobData simulationJobData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.bestsimulation.model.SimulationJobData> toCacheModel();

	@Override
	public org.kisti.edison.bestsimulation.model.SimulationJobData toEscapedModel();

	@Override
	public org.kisti.edison.bestsimulation.model.SimulationJobData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}