/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.bestsimulation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.bestsimulation.service.persistence.SimulationJobStatusPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SimulationJobStatus service. Represents a row in the &quot;EDSIM_SimulationJobStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.bestsimulation.model.impl.SimulationJobStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.bestsimulation.model.impl.SimulationJobStatusImpl}.
 * </p>
 *
 * @author EDISON
 * @see SimulationJobStatus
 * @see org.kisti.edison.bestsimulation.model.impl.SimulationJobStatusImpl
 * @see org.kisti.edison.bestsimulation.model.impl.SimulationJobStatusModelImpl
 * @generated
 */
public interface SimulationJobStatusModel extends BaseModel<SimulationJobStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a simulation job status model instance should use the {@link SimulationJobStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this simulation job status.
	 *
	 * @return the primary key of this simulation job status
	 */
	public SimulationJobStatusPK getPrimaryKey();

	/**
	 * Sets the primary key of this simulation job status.
	 *
	 * @param primaryKey the primary key of this simulation job status
	 */
	public void setPrimaryKey(SimulationJobStatusPK primaryKey);

	/**
	 * Returns the status seq of this simulation job status.
	 *
	 * @return the status seq of this simulation job status
	 */
	public long getStatusSeq();

	/**
	 * Sets the status seq of this simulation job status.
	 *
	 * @param statusSeq the status seq of this simulation job status
	 */
	public void setStatusSeq(long statusSeq);

	/**
	 * Returns the group ID of this simulation job status.
	 *
	 * @return the group ID of this simulation job status
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this simulation job status.
	 *
	 * @param groupId the group ID of this simulation job status
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the simulation uuid of this simulation job status.
	 *
	 * @return the simulation uuid of this simulation job status
	 */
	@AutoEscape
	public String getSimulationUuid();

	/**
	 * Sets the simulation uuid of this simulation job status.
	 *
	 * @param simulationUuid the simulation uuid of this simulation job status
	 */
	public void setSimulationUuid(String simulationUuid);

	/**
	 * Returns the job uuid of this simulation job status.
	 *
	 * @return the job uuid of this simulation job status
	 */
	@AutoEscape
	public String getJobUuid();

	/**
	 * Sets the job uuid of this simulation job status.
	 *
	 * @param jobUuid the job uuid of this simulation job status
	 */
	public void setJobUuid(String jobUuid);

	/**
	 * Returns the job status of this simulation job status.
	 *
	 * @return the job status of this simulation job status
	 */
	public long getJobStatus();

	/**
	 * Sets the job status of this simulation job status.
	 *
	 * @param jobStatus the job status of this simulation job status
	 */
	public void setJobStatus(long jobStatus);

	/**
	 * Returns the job start dt of this simulation job status.
	 *
	 * @return the job start dt of this simulation job status
	 */
	public Date getJobStartDt();

	/**
	 * Sets the job start dt of this simulation job status.
	 *
	 * @param jobStartDt the job start dt of this simulation job status
	 */
	public void setJobStartDt(Date jobStartDt);

	/**
	 * Returns the job end dt of this simulation job status.
	 *
	 * @return the job end dt of this simulation job status
	 */
	public Date getJobEndDt();

	/**
	 * Sets the job end dt of this simulation job status.
	 *
	 * @param jobEndDt the job end dt of this simulation job status
	 */
	public void setJobEndDt(Date jobEndDt);

	/**
	 * Returns the write dt of this simulation job status.
	 *
	 * @return the write dt of this simulation job status
	 */
	public Date getWriteDt();

	/**
	 * Sets the write dt of this simulation job status.
	 *
	 * @param writeDt the write dt of this simulation job status
	 */
	public void setWriteDt(Date writeDt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.bestsimulation.model.SimulationJobStatus simulationJobStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.bestsimulation.model.SimulationJobStatus> toCacheModel();

	@Override
	public org.kisti.edison.bestsimulation.model.SimulationJobStatus toEscapedModel();

	@Override
	public org.kisti.edison.bestsimulation.model.SimulationJobStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}