/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Workflow service. Represents a row in the &quot;EDWF_Workflow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.model.impl.WorkflowModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.model.impl.WorkflowImpl}.
 * </p>
 *
 * @author EDISON
 * @see Workflow
 * @see org.kisti.edison.model.impl.WorkflowImpl
 * @see org.kisti.edison.model.impl.WorkflowModelImpl
 * @generated
 */
public interface WorkflowModel extends BaseModel<Workflow> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workflow model instance should use the {@link Workflow} interface instead.
	 */

	/**
	 * Returns the primary key of this workflow.
	 *
	 * @return the primary key of this workflow
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this workflow.
	 *
	 * @param primaryKey the primary key of this workflow
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the workflow ID of this workflow.
	 *
	 * @return the workflow ID of this workflow
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this workflow.
	 *
	 * @param workflowId the workflow ID of this workflow
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the company ID of this workflow.
	 *
	 * @return the company ID of this workflow
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this workflow.
	 *
	 * @param companyId the company ID of this workflow
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this workflow.
	 *
	 * @return the user ID of this workflow
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this workflow.
	 *
	 * @param userId the user ID of this workflow
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this workflow.
	 *
	 * @return the user uuid of this workflow
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this workflow.
	 *
	 * @param userUuid the user uuid of this workflow
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this workflow.
	 *
	 * @return the create date of this workflow
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this workflow.
	 *
	 * @param createDate the create date of this workflow
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this workflow.
	 *
	 * @return the modified date of this workflow
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this workflow.
	 *
	 * @param modifiedDate the modified date of this workflow
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this workflow.
	 *
	 * @return the title of this workflow
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this workflow in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this workflow
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this workflow in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this workflow. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this workflow in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this workflow
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this workflow in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this workflow
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this workflow.
	 *
	 * @return the locales and localized titles of this workflow
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this workflow.
	 *
	 * @param title the title of this workflow
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this workflow in the language.
	 *
	 * @param title the localized title of this workflow
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this workflow in the language, and sets the default locale.
	 *
	 * @param title the localized title of this workflow
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this workflow from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this workflow
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this workflow from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this workflow
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this workflow.
	 *
	 * @return the description of this workflow
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this workflow in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this workflow
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this workflow in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this workflow. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this workflow in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this workflow
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this workflow in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this workflow
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this workflow.
	 *
	 * @return the locales and localized descriptions of this workflow
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this workflow.
	 *
	 * @param description the description of this workflow
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this workflow in the language.
	 *
	 * @param description the localized description of this workflow
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this workflow in the language, and sets the default locale.
	 *
	 * @param description the localized description of this workflow
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this workflow from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this workflow
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this workflow from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this workflow
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the is public of this workflow.
	 *
	 * @return the is public of this workflow
	 */
	public boolean getIsPublic();

	/**
	 * Returns <code>true</code> if this workflow is is public.
	 *
	 * @return <code>true</code> if this workflow is is public; <code>false</code> otherwise
	 */
	public boolean isIsPublic();

	/**
	 * Sets whether this workflow is is public.
	 *
	 * @param isPublic the is public of this workflow
	 */
	public void setIsPublic(boolean isPublic);

	/**
	 * Returns the parent workflow ID of this workflow.
	 *
	 * @return the parent workflow ID of this workflow
	 */
	public long getParentWorkflowId();

	/**
	 * Sets the parent workflow ID of this workflow.
	 *
	 * @param parentWorkflowId the parent workflow ID of this workflow
	 */
	public void setParentWorkflowId(long parentWorkflowId);

	/**
	 * Returns the screen logic of this workflow.
	 *
	 * @return the screen logic of this workflow
	 */
	@AutoEscape
	public String getScreenLogic();

	/**
	 * Sets the screen logic of this workflow.
	 *
	 * @param screenLogic the screen logic of this workflow
	 */
	public void setScreenLogic(String screenLogic);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(org.kisti.edison.model.Workflow workflow);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.model.Workflow> toCacheModel();

	@Override
	public org.kisti.edison.model.Workflow toEscapedModel();

	@Override
	public org.kisti.edison.model.Workflow toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}