/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.virtuallaboratory.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.kisti.edison.virtuallaboratory.model.VirtualLabClass;
import org.kisti.edison.virtuallaboratory.service.VirtualLabClassLocalServiceUtil;

/**
 * The extended model base implementation for the VirtualLabClass service. Represents a row in the &quot;EDVIR_VirtualLabClass&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VirtualLabClassImpl}.
 * </p>
 *
 * @author EDISON
 * @see VirtualLabClassImpl
 * @see org.kisti.edison.virtuallaboratory.model.VirtualLabClass
 * @generated
 */
public abstract class VirtualLabClassBaseImpl extends VirtualLabClassModelImpl
	implements VirtualLabClass {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a virtual lab class model instance should use the {@link VirtualLabClass} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			VirtualLabClassLocalServiceUtil.addVirtualLabClass(this);
		}
		else {
			VirtualLabClassLocalServiceUtil.updateVirtualLabClass(this);
		}
	}
}