/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.customauthmanager.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import org.kisti.edison.customauthmanager.model.UserGroupRoleCustom;
import org.kisti.edison.customauthmanager.service.UserGroupRoleCustomService;
import org.kisti.edison.customauthmanager.service.persistence.UserGroupRoleCustomFinder;
import org.kisti.edison.customauthmanager.service.persistence.UserGroupRoleCustomPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the user group role custom remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.kisti.edison.customauthmanager.service.impl.UserGroupRoleCustomServiceImpl}.
 * </p>
 *
 * @author EDISON
 * @see org.kisti.edison.customauthmanager.service.impl.UserGroupRoleCustomServiceImpl
 * @see org.kisti.edison.customauthmanager.service.UserGroupRoleCustomServiceUtil
 * @generated
 */
public abstract class UserGroupRoleCustomServiceBaseImpl extends BaseServiceImpl
	implements UserGroupRoleCustomService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.kisti.edison.customauthmanager.service.UserGroupRoleCustomServiceUtil} to access the user group role custom remote service.
	 */

	/**
	 * Returns the user group role custom local service.
	 *
	 * @return the user group role custom local service
	 */
	public org.kisti.edison.customauthmanager.service.UserGroupRoleCustomLocalService getUserGroupRoleCustomLocalService() {
		return userGroupRoleCustomLocalService;
	}

	/**
	 * Sets the user group role custom local service.
	 *
	 * @param userGroupRoleCustomLocalService the user group role custom local service
	 */
	public void setUserGroupRoleCustomLocalService(
		org.kisti.edison.customauthmanager.service.UserGroupRoleCustomLocalService userGroupRoleCustomLocalService) {
		this.userGroupRoleCustomLocalService = userGroupRoleCustomLocalService;
	}

	/**
	 * Returns the user group role custom remote service.
	 *
	 * @return the user group role custom remote service
	 */
	public org.kisti.edison.customauthmanager.service.UserGroupRoleCustomService getUserGroupRoleCustomService() {
		return userGroupRoleCustomService;
	}

	/**
	 * Sets the user group role custom remote service.
	 *
	 * @param userGroupRoleCustomService the user group role custom remote service
	 */
	public void setUserGroupRoleCustomService(
		org.kisti.edison.customauthmanager.service.UserGroupRoleCustomService userGroupRoleCustomService) {
		this.userGroupRoleCustomService = userGroupRoleCustomService;
	}

	/**
	 * Returns the user group role custom persistence.
	 *
	 * @return the user group role custom persistence
	 */
	public UserGroupRoleCustomPersistence getUserGroupRoleCustomPersistence() {
		return userGroupRoleCustomPersistence;
	}

	/**
	 * Sets the user group role custom persistence.
	 *
	 * @param userGroupRoleCustomPersistence the user group role custom persistence
	 */
	public void setUserGroupRoleCustomPersistence(
		UserGroupRoleCustomPersistence userGroupRoleCustomPersistence) {
		this.userGroupRoleCustomPersistence = userGroupRoleCustomPersistence;
	}

	/**
	 * Returns the user group role custom finder.
	 *
	 * @return the user group role custom finder
	 */
	public UserGroupRoleCustomFinder getUserGroupRoleCustomFinder() {
		return userGroupRoleCustomFinder;
	}

	/**
	 * Sets the user group role custom finder.
	 *
	 * @param userGroupRoleCustomFinder the user group role custom finder
	 */
	public void setUserGroupRoleCustomFinder(
		UserGroupRoleCustomFinder userGroupRoleCustomFinder) {
		this.userGroupRoleCustomFinder = userGroupRoleCustomFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return UserGroupRoleCustom.class;
	}

	protected String getModelClassName() {
		return UserGroupRoleCustom.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = userGroupRoleCustomPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.kisti.edison.customauthmanager.service.UserGroupRoleCustomLocalService.class)
	protected org.kisti.edison.customauthmanager.service.UserGroupRoleCustomLocalService userGroupRoleCustomLocalService;
	@BeanReference(type = org.kisti.edison.customauthmanager.service.UserGroupRoleCustomService.class)
	protected org.kisti.edison.customauthmanager.service.UserGroupRoleCustomService userGroupRoleCustomService;
	@BeanReference(type = UserGroupRoleCustomPersistence.class)
	protected UserGroupRoleCustomPersistence userGroupRoleCustomPersistence;
	@BeanReference(type = UserGroupRoleCustomFinder.class)
	protected UserGroupRoleCustomFinder userGroupRoleCustomFinder;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private UserGroupRoleCustomServiceClpInvoker _clpInvoker = new UserGroupRoleCustomServiceClpInvoker();
}