/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.content.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.content.service.persistence.OrgImgContentPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the OrgImgContent service. Represents a row in the &quot;EDMED_OrgImgContent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.content.model.impl.OrgImgContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.content.model.impl.OrgImgContentImpl}.
 * </p>
 *
 * @author EDISON
 * @see OrgImgContent
 * @see org.kisti.edison.content.model.impl.OrgImgContentImpl
 * @see org.kisti.edison.content.model.impl.OrgImgContentModelImpl
 * @generated
 */
public interface OrgImgContentModel extends BaseModel<OrgImgContent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a org img content model instance should use the {@link OrgImgContent} interface instead.
	 */

	/**
	 * Returns the primary key of this org img content.
	 *
	 * @return the primary key of this org img content
	 */
	public OrgImgContentPK getPrimaryKey();

	/**
	 * Sets the primary key of this org img content.
	 *
	 * @param primaryKey the primary key of this org img content
	 */
	public void setPrimaryKey(OrgImgContentPK primaryKey);

	/**
	 * Returns the org img seq of this org img content.
	 *
	 * @return the org img seq of this org img content
	 */
	public long getOrgImgSeq();

	/**
	 * Sets the org img seq of this org img content.
	 *
	 * @param orgImgSeq the org img seq of this org img content
	 */
	public void setOrgImgSeq(long orgImgSeq);

	/**
	 * Returns the group ID of this org img content.
	 *
	 * @return the group ID of this org img content
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this org img content.
	 *
	 * @param groupId the group ID of this org img content
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the order of this org img content.
	 *
	 * @return the order of this org img content
	 */
	public long getOrder();

	/**
	 * Sets the order of this org img content.
	 *
	 * @param order the order of this org img content
	 */
	public void setOrder(long order);

	/**
	 * Returns the org nm of this org img content.
	 *
	 * @return the org nm of this org img content
	 */
	@AutoEscape
	public String getOrgNm();

	/**
	 * Sets the org nm of this org img content.
	 *
	 * @param orgNm the org nm of this org img content
	 */
	public void setOrgNm(String orgNm);

	/**
	 * Returns the org link of this org img content.
	 *
	 * @return the org link of this org img content
	 */
	@AutoEscape
	public String getOrgLink();

	/**
	 * Sets the org link of this org img content.
	 *
	 * @param orgLink the org link of this org img content
	 */
	public void setOrgLink(String orgLink);

	/**
	 * Returns the file entry ID of this org img content.
	 *
	 * @return the file entry ID of this org img content
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this org img content.
	 *
	 * @param fileEntryId the file entry ID of this org img content
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the insert ID of this org img content.
	 *
	 * @return the insert ID of this org img content
	 */
	public long getInsertId();

	/**
	 * Sets the insert ID of this org img content.
	 *
	 * @param insertId the insert ID of this org img content
	 */
	public void setInsertId(long insertId);

	/**
	 * Returns the insert date of this org img content.
	 *
	 * @return the insert date of this org img content
	 */
	public Date getInsertDate();

	/**
	 * Sets the insert date of this org img content.
	 *
	 * @param insertDate the insert date of this org img content
	 */
	public void setInsertDate(Date insertDate);

	/**
	 * Returns the update ID of this org img content.
	 *
	 * @return the update ID of this org img content
	 */
	public long getUpdateId();

	/**
	 * Sets the update ID of this org img content.
	 *
	 * @param updateId the update ID of this org img content
	 */
	public void setUpdateId(long updateId);

	/**
	 * Returns the update date of this org img content.
	 *
	 * @return the update date of this org img content
	 */
	public Date getUpdateDate();

	/**
	 * Sets the update date of this org img content.
	 *
	 * @param updateDate the update date of this org img content
	 */
	public void setUpdateDate(Date updateDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.content.model.OrgImgContent orgImgContent);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.content.model.OrgImgContent> toCacheModel();

	@Override
	public org.kisti.edison.content.model.OrgImgContent toEscapedModel();

	@Override
	public org.kisti.edison.content.model.OrgImgContent toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}