/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model.impl;

import com.kisti.science.platform.app.model.CommonModule;
import com.kisti.science.platform.app.model.CommonModuleModel;
import com.kisti.science.platform.app.model.CommonModuleSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CommonModule service. Represents a row in the &quot;ScienceApp_CommonModule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.kisti.science.platform.app.model.CommonModuleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommonModuleImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see CommonModuleImpl
 * @see com.kisti.science.platform.app.model.CommonModule
 * @see com.kisti.science.platform.app.model.CommonModuleModel
 * @generated
 */
@JSON(strict = true)
public class CommonModuleModelImpl extends BaseModelImpl<CommonModule>
	implements CommonModuleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a common module model instance should use the {@link com.kisti.science.platform.app.model.CommonModule} interface instead.
	 */
	public static final String TABLE_NAME = "ScienceApp_CommonModule";
	public static final Object[][] TABLE_COLUMNS = {
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "moduleName", Types.VARCHAR },
			{ "moduleRootDir", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ScienceApp_CommonModule (groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,moduleName VARCHAR(75) not null primary key,moduleRootDir VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ScienceApp_CommonModule";
	public static final String ORDER_BY_JPQL = " ORDER BY commonModule.moduleName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ScienceApp_CommonModule.moduleName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.science.platform.app.model.CommonModule"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.science.platform.app.model.CommonModule"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.kisti.science.platform.app.model.CommonModule"),
			true);
	public static long MODULENAME_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CommonModule toModel(CommonModuleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CommonModule model = new CommonModuleImpl();

		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModuleName(soapModel.getModuleName());
		model.setModuleRootDir(soapModel.getModuleRootDir());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CommonModule> toModels(CommonModuleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CommonModule> models = new ArrayList<CommonModule>(soapModels.length);

		for (CommonModuleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.kisti.science.platform.app.model.CommonModule"));

	public CommonModuleModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _moduleName;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setModuleName(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _moduleName;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CommonModule.class;
	}

	@Override
	public String getModelClassName() {
		return CommonModule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("moduleName", getModuleName());
		attributes.put("moduleRootDir", getModuleRootDir());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String moduleName = (String)attributes.get("moduleName");

		if (moduleName != null) {
			setModuleName(moduleName);
		}

		String moduleRootDir = (String)attributes.get("moduleRootDir");

		if (moduleRootDir != null) {
			setModuleRootDir(moduleRootDir);
		}
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getModuleName() {
		if (_moduleName == null) {
			return StringPool.BLANK;
		}
		else {
			return _moduleName;
		}
	}

	@Override
	public void setModuleName(String moduleName) {
		_columnBitmask |= MODULENAME_COLUMN_BITMASK;

		if (_originalModuleName == null) {
			_originalModuleName = _moduleName;
		}

		_moduleName = moduleName;
	}

	public String getOriginalModuleName() {
		return GetterUtil.getString(_originalModuleName);
	}

	@JSON
	@Override
	public String getModuleRootDir() {
		if (_moduleRootDir == null) {
			return StringPool.BLANK;
		}
		else {
			return _moduleRootDir;
		}
	}

	@Override
	public void setModuleRootDir(String moduleRootDir) {
		_moduleRootDir = moduleRootDir;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CommonModule toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CommonModule)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommonModuleImpl commonModuleImpl = new CommonModuleImpl();

		commonModuleImpl.setGroupId(getGroupId());
		commonModuleImpl.setCompanyId(getCompanyId());
		commonModuleImpl.setUserId(getUserId());
		commonModuleImpl.setUserName(getUserName());
		commonModuleImpl.setCreateDate(getCreateDate());
		commonModuleImpl.setModifiedDate(getModifiedDate());
		commonModuleImpl.setModuleName(getModuleName());
		commonModuleImpl.setModuleRootDir(getModuleRootDir());

		commonModuleImpl.resetOriginalValues();

		return commonModuleImpl;
	}

	@Override
	public int compareTo(CommonModule commonModule) {
		String primaryKey = commonModule.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CommonModule)) {
			return false;
		}

		CommonModule commonModule = (CommonModule)obj;

		String primaryKey = commonModule.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		CommonModuleModelImpl commonModuleModelImpl = this;

		commonModuleModelImpl._originalModuleName = commonModuleModelImpl._moduleName;

		commonModuleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CommonModule> toCacheModel() {
		CommonModuleCacheModel commonModuleCacheModel = new CommonModuleCacheModel();

		commonModuleCacheModel.groupId = getGroupId();

		commonModuleCacheModel.companyId = getCompanyId();

		commonModuleCacheModel.userId = getUserId();

		commonModuleCacheModel.userName = getUserName();

		String userName = commonModuleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			commonModuleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			commonModuleCacheModel.createDate = createDate.getTime();
		}
		else {
			commonModuleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			commonModuleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			commonModuleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		commonModuleCacheModel.moduleName = getModuleName();

		String moduleName = commonModuleCacheModel.moduleName;

		if ((moduleName != null) && (moduleName.length() == 0)) {
			commonModuleCacheModel.moduleName = null;
		}

		commonModuleCacheModel.moduleRootDir = getModuleRootDir();

		String moduleRootDir = commonModuleCacheModel.moduleRootDir;

		if ((moduleRootDir != null) && (moduleRootDir.length() == 0)) {
			commonModuleCacheModel.moduleRootDir = null;
		}

		return commonModuleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", moduleName=");
		sb.append(getModuleName());
		sb.append(", moduleRootDir=");
		sb.append(getModuleRootDir());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.kisti.science.platform.app.model.CommonModule");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moduleName</column-name><column-value><![CDATA[");
		sb.append(getModuleName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moduleRootDir</column-name><column-value><![CDATA[");
		sb.append(getModuleRootDir());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CommonModule.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CommonModule.class
		};
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _moduleName;
	private String _originalModuleName;
	private String _moduleRootDir;
	private long _columnBitmask;
	private CommonModule _escapedModel;
}