/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model.impl;

import com.kisti.science.platform.app.model.PortTypeEditorLink;
import com.kisti.science.platform.app.model.PortTypeEditorLinkModel;
import com.kisti.science.platform.app.model.PortTypeEditorLinkSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PortTypeEditorLink service. Represents a row in the &quot;ScienceApp_PortTypeEditorLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.kisti.science.platform.app.model.PortTypeEditorLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PortTypeEditorLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see PortTypeEditorLinkImpl
 * @see com.kisti.science.platform.app.model.PortTypeEditorLink
 * @see com.kisti.science.platform.app.model.PortTypeEditorLinkModel
 * @generated
 */
@JSON(strict = true)
public class PortTypeEditorLinkModelImpl extends BaseModelImpl<PortTypeEditorLink>
	implements PortTypeEditorLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a port type editor link model instance should use the {@link com.kisti.science.platform.app.model.PortTypeEditorLink} interface instead.
	 */
	public static final String TABLE_NAME = "ScienceApp_PortTypeEditorLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "portTypeEditorLinkId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "portTypeId", Types.BIGINT },
			{ "editorId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ScienceApp_PortTypeEditorLink (uuid_ VARCHAR(75) null,portTypeEditorLinkId LONG not null primary key,companyId LONG,portTypeId LONG,editorId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ScienceApp_PortTypeEditorLink";
	public static final String ORDER_BY_JPQL = " ORDER BY portTypeEditorLink.portTypeEditorLinkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ScienceApp_PortTypeEditorLink.portTypeEditorLinkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.science.platform.app.model.PortTypeEditorLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.science.platform.app.model.PortTypeEditorLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.kisti.science.platform.app.model.PortTypeEditorLink"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long PORTTYPEID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long PORTTYPEEDITORLINKID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PortTypeEditorLink toModel(PortTypeEditorLinkSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PortTypeEditorLink model = new PortTypeEditorLinkImpl();

		model.setUuid(soapModel.getUuid());
		model.setPortTypeEditorLinkId(soapModel.getPortTypeEditorLinkId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setPortTypeId(soapModel.getPortTypeId());
		model.setEditorId(soapModel.getEditorId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PortTypeEditorLink> toModels(
		PortTypeEditorLinkSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<PortTypeEditorLink> models = new ArrayList<PortTypeEditorLink>(soapModels.length);

		for (PortTypeEditorLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.kisti.science.platform.app.model.PortTypeEditorLink"));

	public PortTypeEditorLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _portTypeEditorLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPortTypeEditorLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _portTypeEditorLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PortTypeEditorLink.class;
	}

	@Override
	public String getModelClassName() {
		return PortTypeEditorLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("portTypeEditorLinkId", getPortTypeEditorLinkId());
		attributes.put("companyId", getCompanyId());
		attributes.put("portTypeId", getPortTypeId());
		attributes.put("editorId", getEditorId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long portTypeEditorLinkId = (Long)attributes.get("portTypeEditorLinkId");

		if (portTypeEditorLinkId != null) {
			setPortTypeEditorLinkId(portTypeEditorLinkId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long portTypeId = (Long)attributes.get("portTypeId");

		if (portTypeId != null) {
			setPortTypeId(portTypeId);
		}

		Long editorId = (Long)attributes.get("editorId");

		if (editorId != null) {
			setEditorId(editorId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPortTypeEditorLinkId() {
		return _portTypeEditorLinkId;
	}

	@Override
	public void setPortTypeEditorLinkId(long portTypeEditorLinkId) {
		_portTypeEditorLinkId = portTypeEditorLinkId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getPortTypeId() {
		return _portTypeId;
	}

	@Override
	public void setPortTypeId(long portTypeId) {
		_columnBitmask |= PORTTYPEID_COLUMN_BITMASK;

		if (!_setOriginalPortTypeId) {
			_setOriginalPortTypeId = true;

			_originalPortTypeId = _portTypeId;
		}

		_portTypeId = portTypeId;
	}

	public long getOriginalPortTypeId() {
		return _originalPortTypeId;
	}

	@JSON
	@Override
	public long getEditorId() {
		return _editorId;
	}

	@Override
	public void setEditorId(long editorId) {
		_editorId = editorId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PortTypeEditorLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PortTypeEditorLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PortTypeEditorLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PortTypeEditorLinkImpl portTypeEditorLinkImpl = new PortTypeEditorLinkImpl();

		portTypeEditorLinkImpl.setUuid(getUuid());
		portTypeEditorLinkImpl.setPortTypeEditorLinkId(getPortTypeEditorLinkId());
		portTypeEditorLinkImpl.setCompanyId(getCompanyId());
		portTypeEditorLinkImpl.setPortTypeId(getPortTypeId());
		portTypeEditorLinkImpl.setEditorId(getEditorId());

		portTypeEditorLinkImpl.resetOriginalValues();

		return portTypeEditorLinkImpl;
	}

	@Override
	public int compareTo(PortTypeEditorLink portTypeEditorLink) {
		long primaryKey = portTypeEditorLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PortTypeEditorLink)) {
			return false;
		}

		PortTypeEditorLink portTypeEditorLink = (PortTypeEditorLink)obj;

		long primaryKey = portTypeEditorLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PortTypeEditorLinkModelImpl portTypeEditorLinkModelImpl = this;

		portTypeEditorLinkModelImpl._originalUuid = portTypeEditorLinkModelImpl._uuid;

		portTypeEditorLinkModelImpl._originalCompanyId = portTypeEditorLinkModelImpl._companyId;

		portTypeEditorLinkModelImpl._setOriginalCompanyId = false;

		portTypeEditorLinkModelImpl._originalPortTypeId = portTypeEditorLinkModelImpl._portTypeId;

		portTypeEditorLinkModelImpl._setOriginalPortTypeId = false;

		portTypeEditorLinkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PortTypeEditorLink> toCacheModel() {
		PortTypeEditorLinkCacheModel portTypeEditorLinkCacheModel = new PortTypeEditorLinkCacheModel();

		portTypeEditorLinkCacheModel.uuid = getUuid();

		String uuid = portTypeEditorLinkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			portTypeEditorLinkCacheModel.uuid = null;
		}

		portTypeEditorLinkCacheModel.portTypeEditorLinkId = getPortTypeEditorLinkId();

		portTypeEditorLinkCacheModel.companyId = getCompanyId();

		portTypeEditorLinkCacheModel.portTypeId = getPortTypeId();

		portTypeEditorLinkCacheModel.editorId = getEditorId();

		return portTypeEditorLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", portTypeEditorLinkId=");
		sb.append(getPortTypeEditorLinkId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", portTypeId=");
		sb.append(getPortTypeId());
		sb.append(", editorId=");
		sb.append(getEditorId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.kisti.science.platform.app.model.PortTypeEditorLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portTypeEditorLinkId</column-name><column-value><![CDATA[");
		sb.append(getPortTypeEditorLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portTypeId</column-name><column-value><![CDATA[");
		sb.append(getPortTypeId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>editorId</column-name><column-value><![CDATA[");
		sb.append(getEditorId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PortTypeEditorLink.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PortTypeEditorLink.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _portTypeEditorLinkId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _portTypeId;
	private long _originalPortTypeId;
	private boolean _setOriginalPortTypeId;
	private long _editorId;
	private long _columnBitmask;
	private PortTypeEditorLink _escapedModel;
}