/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model.impl;

import com.kisti.science.platform.app.model.ScienceAppCategoryLink;
import com.kisti.science.platform.app.service.ScienceAppCategoryLinkLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ScienceAppCategoryLink service. Represents a row in the &quot;ScienceApp_ScienceAppCategoryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppCategoryLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see ScienceAppCategoryLinkImpl
 * @see com.kisti.science.platform.app.model.ScienceAppCategoryLink
 * @generated
 */
public abstract class ScienceAppCategoryLinkBaseImpl
	extends ScienceAppCategoryLinkModelImpl implements ScienceAppCategoryLink {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app category link model instance should use the {@link ScienceAppCategoryLink} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ScienceAppCategoryLinkLocalServiceUtil.addScienceAppCategoryLink(this);
		}
		else {
			ScienceAppCategoryLinkLocalServiceUtil.updateScienceAppCategoryLink(this);
		}
	}
}