/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model.impl;

import com.kisti.science.platform.app.model.ScienceAppManager;
import com.kisti.science.platform.app.model.ScienceAppManagerModel;
import com.kisti.science.platform.app.model.ScienceAppManagerSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ScienceAppManager service. Represents a row in the &quot;ScienceApp_ScienceAppManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.kisti.science.platform.app.model.ScienceAppManagerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppManagerImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see ScienceAppManagerImpl
 * @see com.kisti.science.platform.app.model.ScienceAppManager
 * @see com.kisti.science.platform.app.model.ScienceAppManagerModel
 * @generated
 */
@JSON(strict = true)
public class ScienceAppManagerModelImpl extends BaseModelImpl<ScienceAppManager>
	implements ScienceAppManagerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app manager model instance should use the {@link com.kisti.science.platform.app.model.ScienceAppManager} interface instead.
	 */
	public static final String TABLE_NAME = "ScienceApp_ScienceAppManager";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scienceAppManagerId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "scienceAppId", Types.BIGINT },
			{ "managerId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table ScienceApp_ScienceAppManager (scienceAppManagerId LONG not null primary key,userId LONG,createDate DATE null,scienceAppId LONG,managerId LONG)";
	public static final String TABLE_SQL_DROP = "drop table ScienceApp_ScienceAppManager";
	public static final String ORDER_BY_JPQL = " ORDER BY scienceAppManager.scienceAppManagerId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ScienceApp_ScienceAppManager.scienceAppManagerId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.science.platform.app.model.ScienceAppManager"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.science.platform.app.model.ScienceAppManager"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.kisti.science.platform.app.model.ScienceAppManager"),
			true);
	public static long MANAGERID_COLUMN_BITMASK = 1L;
	public static long SCIENCEAPPID_COLUMN_BITMASK = 2L;
	public static long SCIENCEAPPMANAGERID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ScienceAppManager toModel(ScienceAppManagerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ScienceAppManager model = new ScienceAppManagerImpl();

		model.setScienceAppManagerId(soapModel.getScienceAppManagerId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setScienceAppId(soapModel.getScienceAppId());
		model.setManagerId(soapModel.getManagerId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ScienceAppManager> toModels(
		ScienceAppManagerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ScienceAppManager> models = new ArrayList<ScienceAppManager>(soapModels.length);

		for (ScienceAppManagerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.kisti.science.platform.app.model.ScienceAppManager"));

	public ScienceAppManagerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppManagerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppManagerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppManagerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScienceAppManager.class;
	}

	@Override
	public String getModelClassName() {
		return ScienceAppManager.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scienceAppManagerId", getScienceAppManagerId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("scienceAppId", getScienceAppId());
		attributes.put("managerId", getManagerId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scienceAppManagerId = (Long)attributes.get("scienceAppManagerId");

		if (scienceAppManagerId != null) {
			setScienceAppManagerId(scienceAppManagerId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long scienceAppId = (Long)attributes.get("scienceAppId");

		if (scienceAppId != null) {
			setScienceAppId(scienceAppId);
		}

		Long managerId = (Long)attributes.get("managerId");

		if (managerId != null) {
			setManagerId(managerId);
		}
	}

	@JSON
	@Override
	public long getScienceAppManagerId() {
		return _scienceAppManagerId;
	}

	@Override
	public void setScienceAppManagerId(long scienceAppManagerId) {
		_scienceAppManagerId = scienceAppManagerId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_columnBitmask |= SCIENCEAPPID_COLUMN_BITMASK;

		if (!_setOriginalScienceAppId) {
			_setOriginalScienceAppId = true;

			_originalScienceAppId = _scienceAppId;
		}

		_scienceAppId = scienceAppId;
	}

	public long getOriginalScienceAppId() {
		return _originalScienceAppId;
	}

	@JSON
	@Override
	public long getManagerId() {
		return _managerId;
	}

	@Override
	public void setManagerId(long managerId) {
		_columnBitmask |= MANAGERID_COLUMN_BITMASK;

		if (!_setOriginalManagerId) {
			_setOriginalManagerId = true;

			_originalManagerId = _managerId;
		}

		_managerId = managerId;
	}

	public long getOriginalManagerId() {
		return _originalManagerId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ScienceAppManager.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScienceAppManager toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ScienceAppManager)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScienceAppManagerImpl scienceAppManagerImpl = new ScienceAppManagerImpl();

		scienceAppManagerImpl.setScienceAppManagerId(getScienceAppManagerId());
		scienceAppManagerImpl.setUserId(getUserId());
		scienceAppManagerImpl.setCreateDate(getCreateDate());
		scienceAppManagerImpl.setScienceAppId(getScienceAppId());
		scienceAppManagerImpl.setManagerId(getManagerId());

		scienceAppManagerImpl.resetOriginalValues();

		return scienceAppManagerImpl;
	}

	@Override
	public int compareTo(ScienceAppManager scienceAppManager) {
		long primaryKey = scienceAppManager.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScienceAppManager)) {
			return false;
		}

		ScienceAppManager scienceAppManager = (ScienceAppManager)obj;

		long primaryKey = scienceAppManager.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ScienceAppManagerModelImpl scienceAppManagerModelImpl = this;

		scienceAppManagerModelImpl._originalScienceAppId = scienceAppManagerModelImpl._scienceAppId;

		scienceAppManagerModelImpl._setOriginalScienceAppId = false;

		scienceAppManagerModelImpl._originalManagerId = scienceAppManagerModelImpl._managerId;

		scienceAppManagerModelImpl._setOriginalManagerId = false;

		scienceAppManagerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ScienceAppManager> toCacheModel() {
		ScienceAppManagerCacheModel scienceAppManagerCacheModel = new ScienceAppManagerCacheModel();

		scienceAppManagerCacheModel.scienceAppManagerId = getScienceAppManagerId();

		scienceAppManagerCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			scienceAppManagerCacheModel.createDate = createDate.getTime();
		}
		else {
			scienceAppManagerCacheModel.createDate = Long.MIN_VALUE;
		}

		scienceAppManagerCacheModel.scienceAppId = getScienceAppId();

		scienceAppManagerCacheModel.managerId = getManagerId();

		return scienceAppManagerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{scienceAppManagerId=");
		sb.append(getScienceAppManagerId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", scienceAppId=");
		sb.append(getScienceAppId());
		sb.append(", managerId=");
		sb.append(getManagerId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.kisti.science.platform.app.model.ScienceAppManager");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scienceAppManagerId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppManagerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scienceAppId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>managerId</column-name><column-value><![CDATA[");
		sb.append(getManagerId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ScienceAppManager.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ScienceAppManager.class
		};
	private long _scienceAppManagerId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private long _scienceAppId;
	private long _originalScienceAppId;
	private boolean _setOriginalScienceAppId;
	private long _managerId;
	private long _originalManagerId;
	private boolean _setOriginalManagerId;
	private long _columnBitmask;
	private ScienceAppManager _escapedModel;
}