/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model.impl;

import com.kisti.science.platform.app.model.ScienceAppInputPorts;
import com.kisti.science.platform.app.model.ScienceAppInputPortsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ScienceAppInputPorts service. Represents a row in the &quot;ScienceApp_ScienceAppInputPorts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.kisti.science.platform.app.model.ScienceAppInputPortsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppInputPortsImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see ScienceAppInputPortsImpl
 * @see com.kisti.science.platform.app.model.ScienceAppInputPorts
 * @see com.kisti.science.platform.app.model.ScienceAppInputPortsModel
 * @generated
 */
public class ScienceAppInputPortsModelImpl extends BaseModelImpl<ScienceAppInputPorts>
	implements ScienceAppInputPortsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app input ports model instance should use the {@link com.kisti.science.platform.app.model.ScienceAppInputPorts} interface instead.
	 */
	public static final String TABLE_NAME = "ScienceApp_ScienceAppInputPorts";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scienceAppId", Types.BIGINT },
			{ "inputPorts", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ScienceApp_ScienceAppInputPorts (scienceAppId LONG not null primary key,inputPorts VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ScienceApp_ScienceAppInputPorts";
	public static final String ORDER_BY_JPQL = " ORDER BY scienceAppInputPorts.scienceAppId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY ScienceApp_ScienceAppInputPorts.scienceAppId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.science.platform.app.model.ScienceAppInputPorts"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.science.platform.app.model.ScienceAppInputPorts"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.kisti.science.platform.app.model.ScienceAppInputPorts"));

	public ScienceAppInputPortsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScienceAppInputPorts.class;
	}

	@Override
	public String getModelClassName() {
		return ScienceAppInputPorts.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scienceAppId", getScienceAppId());
		attributes.put("inputPorts", getInputPorts());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scienceAppId = (Long)attributes.get("scienceAppId");

		if (scienceAppId != null) {
			setScienceAppId(scienceAppId);
		}

		String inputPorts = (String)attributes.get("inputPorts");

		if (inputPorts != null) {
			setInputPorts(inputPorts);
		}
	}

	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_scienceAppId = scienceAppId;
	}

	@Override
	public String getInputPorts() {
		if (_inputPorts == null) {
			return StringPool.BLANK;
		}
		else {
			return _inputPorts;
		}
	}

	@Override
	public void setInputPorts(String inputPorts) {
		_inputPorts = inputPorts;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ScienceAppInputPorts.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScienceAppInputPorts toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ScienceAppInputPorts)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScienceAppInputPortsImpl scienceAppInputPortsImpl = new ScienceAppInputPortsImpl();

		scienceAppInputPortsImpl.setScienceAppId(getScienceAppId());
		scienceAppInputPortsImpl.setInputPorts(getInputPorts());

		scienceAppInputPortsImpl.resetOriginalValues();

		return scienceAppInputPortsImpl;
	}

	@Override
	public int compareTo(ScienceAppInputPorts scienceAppInputPorts) {
		long primaryKey = scienceAppInputPorts.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScienceAppInputPorts)) {
			return false;
		}

		ScienceAppInputPorts scienceAppInputPorts = (ScienceAppInputPorts)obj;

		long primaryKey = scienceAppInputPorts.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<ScienceAppInputPorts> toCacheModel() {
		ScienceAppInputPortsCacheModel scienceAppInputPortsCacheModel = new ScienceAppInputPortsCacheModel();

		scienceAppInputPortsCacheModel.scienceAppId = getScienceAppId();

		scienceAppInputPortsCacheModel.inputPorts = getInputPorts();

		String inputPorts = scienceAppInputPortsCacheModel.inputPorts;

		if ((inputPorts != null) && (inputPorts.length() == 0)) {
			scienceAppInputPortsCacheModel.inputPorts = null;
		}

		return scienceAppInputPortsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{scienceAppId=");
		sb.append(getScienceAppId());
		sb.append(", inputPorts=");
		sb.append(getInputPorts());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.kisti.science.platform.app.model.ScienceAppInputPorts");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scienceAppId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>inputPorts</column-name><column-value><![CDATA[");
		sb.append(getInputPorts());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ScienceAppInputPorts.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ScienceAppInputPorts.class
		};
	private long _scienceAppId;
	private String _inputPorts;
	private ScienceAppInputPorts _escapedModel;
}