/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.model.impl;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.kisti.edison.model.WorkflowInstance;
import org.kisti.edison.model.WorkflowInstanceModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the WorkflowInstance service. Represents a row in the &quot;EDWF_WorkflowInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.kisti.edison.model.WorkflowInstanceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorkflowInstanceImpl}.
 * </p>
 *
 * @author EDISON
 * @see WorkflowInstanceImpl
 * @see org.kisti.edison.model.WorkflowInstance
 * @see org.kisti.edison.model.WorkflowInstanceModel
 * @generated
 */
public class WorkflowInstanceModelImpl extends BaseModelImpl<WorkflowInstance>
	implements WorkflowInstanceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a workflow instance model instance should use the {@link org.kisti.edison.model.WorkflowInstance} interface instead.
	 */
	public static final String TABLE_NAME = "EDWF_WorkflowInstance";
	public static final Object[][] TABLE_COLUMNS = {
			{ "workflowInstanceId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "title", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "startTime", Types.TIMESTAMP },
			{ "endTime", Types.TIMESTAMP },
			{ "workflowId", Types.BIGINT },
			{ "workflowUUID", Types.VARCHAR },
			{ "screenLogic", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table EDWF_WorkflowInstance (workflowInstanceId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,title STRING null,status STRING null,startTime DATE null,endTime DATE null,workflowId LONG,workflowUUID VARCHAR(75) null,screenLogic TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table EDWF_WorkflowInstance";
	public static final String ORDER_BY_JPQL = " ORDER BY workflowInstance.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY EDWF_WorkflowInstance.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.kisti.edison.model.WorkflowInstance"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.kisti.edison.model.WorkflowInstance"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.kisti.edison.model.WorkflowInstance"),
			true);
	public static long TITLE_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;
	public static final String MAPPING_TABLE_EDWF_WORKFLOW_WORKFLOWINSTANCE_NAME =
		"EDWF_Workflow_WorkflowInstance";
	public static final Object[][] MAPPING_TABLE_EDWF_WORKFLOW_WORKFLOWINSTANCE_COLUMNS =
		{
			{ "workflowId", Types.BIGINT },
			{ "workflowInstanceId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_EDWF_WORKFLOW_WORKFLOWINSTANCE_SQL_CREATE =
		"create table EDWF_Workflow_WorkflowInstance (workflowId LONG not null,workflowInstanceId LONG not null,primary key (workflowId, workflowInstanceId))";
	public static final boolean FINDER_CACHE_ENABLED_EDWF_WORKFLOW_WORKFLOWINSTANCE =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.EDWF_Workflow_WorkflowInstance"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.kisti.edison.model.WorkflowInstance"));

	public WorkflowInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workflowInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkflowInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workflowInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return WorkflowInstance.class;
	}

	@Override
	public String getModelClassName() {
		return WorkflowInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("workflowInstanceId", getWorkflowInstanceId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("title", getTitle());
		attributes.put("status", getStatus());
		attributes.put("startTime", getStartTime());
		attributes.put("endTime", getEndTime());
		attributes.put("workflowId", getWorkflowId());
		attributes.put("workflowUUID", getWorkflowUUID());
		attributes.put("screenLogic", getScreenLogic());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long workflowInstanceId = (Long)attributes.get("workflowInstanceId");

		if (workflowInstanceId != null) {
			setWorkflowInstanceId(workflowInstanceId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Date startTime = (Date)attributes.get("startTime");

		if (startTime != null) {
			setStartTime(startTime);
		}

		Date endTime = (Date)attributes.get("endTime");

		if (endTime != null) {
			setEndTime(endTime);
		}

		Long workflowId = (Long)attributes.get("workflowId");

		if (workflowId != null) {
			setWorkflowId(workflowId);
		}

		String workflowUUID = (String)attributes.get("workflowUUID");

		if (workflowUUID != null) {
			setWorkflowUUID(workflowUUID);
		}

		String screenLogic = (String)attributes.get("screenLogic");

		if (screenLogic != null) {
			setScreenLogic(screenLogic);
		}
	}

	@Override
	public long getWorkflowInstanceId() {
		return _workflowInstanceId;
	}

	@Override
	public void setWorkflowInstanceId(long workflowInstanceId) {
		_workflowInstanceId = workflowInstanceId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getTitle(), languageId,
			useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(LocalizationUtil.updateLocalization(getTitle(), "Title",
					title, languageId, defaultLanguageId));
		}
		else {
			setTitle(LocalizationUtil.removeLocalization(getTitle(), "Title",
					languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale) {
		if (titleMap == null) {
			return;
		}

		setTitle(LocalizationUtil.updateLocalization(titleMap, getTitle(),
				"Title", LocaleUtil.toLanguageId(defaultLocale)));
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public String getStatus(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getStatus(languageId);
	}

	@Override
	public String getStatus(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getStatus(languageId, useDefault);
	}

	@Override
	public String getStatus(String languageId) {
		return LocalizationUtil.getLocalization(getStatus(), languageId);
	}

	@Override
	public String getStatus(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getStatus(), languageId,
			useDefault);
	}

	@Override
	public String getStatusCurrentLanguageId() {
		return _statusCurrentLanguageId;
	}

	@JSON
	@Override
	public String getStatusCurrentValue() {
		Locale locale = getLocale(_statusCurrentLanguageId);

		return getStatus(locale);
	}

	@Override
	public Map<Locale, String> getStatusMap() {
		return LocalizationUtil.getLocalizationMap(getStatus());
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public void setStatus(String status, Locale locale) {
		setStatus(status, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setStatus(String status, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(status)) {
			setStatus(LocalizationUtil.updateLocalization(getStatus(),
					"Status", status, languageId, defaultLanguageId));
		}
		else {
			setStatus(LocalizationUtil.removeLocalization(getStatus(),
					"Status", languageId));
		}
	}

	@Override
	public void setStatusCurrentLanguageId(String languageId) {
		_statusCurrentLanguageId = languageId;
	}

	@Override
	public void setStatusMap(Map<Locale, String> statusMap) {
		setStatusMap(statusMap, LocaleUtil.getDefault());
	}

	@Override
	public void setStatusMap(Map<Locale, String> statusMap, Locale defaultLocale) {
		if (statusMap == null) {
			return;
		}

		setStatus(LocalizationUtil.updateLocalization(statusMap, getStatus(),
				"Status", LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public Date getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(Date startTime) {
		_startTime = startTime;
	}

	@Override
	public Date getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(Date endTime) {
		_endTime = endTime;
	}

	@Override
	public long getWorkflowId() {
		return _workflowId;
	}

	@Override
	public void setWorkflowId(long workflowId) {
		_workflowId = workflowId;
	}

	@Override
	public String getWorkflowUUID() {
		if (_workflowUUID == null) {
			return StringPool.BLANK;
		}
		else {
			return _workflowUUID;
		}
	}

	@Override
	public void setWorkflowUUID(String workflowUUID) {
		_workflowUUID = workflowUUID;
	}

	@Override
	public String getScreenLogic() {
		if (_screenLogic == null) {
			return StringPool.BLANK;
		}
		else {
			return _screenLogic;
		}
	}

	@Override
	public void setScreenLogic(String screenLogic) {
		_screenLogic = screenLogic;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			WorkflowInstance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> statusMap = getStatusMap();

		for (Map.Entry<Locale, String> entry : statusMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		prepareLocalizedFieldsForImport(null);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String status = getStatus(defaultLocale);

		if (Validator.isNull(status)) {
			setStatus(getStatus(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setStatus(getStatus(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public WorkflowInstance toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (WorkflowInstance)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		WorkflowInstanceImpl workflowInstanceImpl = new WorkflowInstanceImpl();

		workflowInstanceImpl.setWorkflowInstanceId(getWorkflowInstanceId());
		workflowInstanceImpl.setCompanyId(getCompanyId());
		workflowInstanceImpl.setUserId(getUserId());
		workflowInstanceImpl.setCreateDate(getCreateDate());
		workflowInstanceImpl.setModifiedDate(getModifiedDate());
		workflowInstanceImpl.setTitle(getTitle());
		workflowInstanceImpl.setStatus(getStatus());
		workflowInstanceImpl.setStartTime(getStartTime());
		workflowInstanceImpl.setEndTime(getEndTime());
		workflowInstanceImpl.setWorkflowId(getWorkflowId());
		workflowInstanceImpl.setWorkflowUUID(getWorkflowUUID());
		workflowInstanceImpl.setScreenLogic(getScreenLogic());

		workflowInstanceImpl.resetOriginalValues();

		return workflowInstanceImpl;
	}

	@Override
	public int compareTo(WorkflowInstance workflowInstance) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				workflowInstance.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof WorkflowInstance)) {
			return false;
		}

		WorkflowInstance workflowInstance = (WorkflowInstance)obj;

		long primaryKey = workflowInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		WorkflowInstanceModelImpl workflowInstanceModelImpl = this;

		workflowInstanceModelImpl._originalUserId = workflowInstanceModelImpl._userId;

		workflowInstanceModelImpl._setOriginalUserId = false;

		workflowInstanceModelImpl._originalTitle = workflowInstanceModelImpl._title;

		workflowInstanceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<WorkflowInstance> toCacheModel() {
		WorkflowInstanceCacheModel workflowInstanceCacheModel = new WorkflowInstanceCacheModel();

		workflowInstanceCacheModel.workflowInstanceId = getWorkflowInstanceId();

		workflowInstanceCacheModel.companyId = getCompanyId();

		workflowInstanceCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			workflowInstanceCacheModel.createDate = createDate.getTime();
		}
		else {
			workflowInstanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			workflowInstanceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			workflowInstanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		workflowInstanceCacheModel.title = getTitle();

		String title = workflowInstanceCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			workflowInstanceCacheModel.title = null;
		}

		workflowInstanceCacheModel.status = getStatus();

		String status = workflowInstanceCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			workflowInstanceCacheModel.status = null;
		}

		Date startTime = getStartTime();

		if (startTime != null) {
			workflowInstanceCacheModel.startTime = startTime.getTime();
		}
		else {
			workflowInstanceCacheModel.startTime = Long.MIN_VALUE;
		}

		Date endTime = getEndTime();

		if (endTime != null) {
			workflowInstanceCacheModel.endTime = endTime.getTime();
		}
		else {
			workflowInstanceCacheModel.endTime = Long.MIN_VALUE;
		}

		workflowInstanceCacheModel.workflowId = getWorkflowId();

		workflowInstanceCacheModel.workflowUUID = getWorkflowUUID();

		String workflowUUID = workflowInstanceCacheModel.workflowUUID;

		if ((workflowUUID != null) && (workflowUUID.length() == 0)) {
			workflowInstanceCacheModel.workflowUUID = null;
		}

		workflowInstanceCacheModel.screenLogic = getScreenLogic();

		String screenLogic = workflowInstanceCacheModel.screenLogic;

		if ((screenLogic != null) && (screenLogic.length() == 0)) {
			workflowInstanceCacheModel.screenLogic = null;
		}

		return workflowInstanceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{workflowInstanceId=");
		sb.append(getWorkflowInstanceId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", startTime=");
		sb.append(getStartTime());
		sb.append(", endTime=");
		sb.append(getEndTime());
		sb.append(", workflowId=");
		sb.append(getWorkflowId());
		sb.append(", workflowUUID=");
		sb.append(getWorkflowUUID());
		sb.append(", screenLogic=");
		sb.append(getScreenLogic());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("org.kisti.edison.model.WorkflowInstance");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>workflowInstanceId</column-name><column-value><![CDATA[");
		sb.append(getWorkflowInstanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startTime</column-name><column-value><![CDATA[");
		sb.append(getStartTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endTime</column-name><column-value><![CDATA[");
		sb.append(getEndTime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workflowId</column-name><column-value><![CDATA[");
		sb.append(getWorkflowId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>workflowUUID</column-name><column-value><![CDATA[");
		sb.append(getWorkflowUUID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>screenLogic</column-name><column-value><![CDATA[");
		sb.append(getScreenLogic());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = WorkflowInstance.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			WorkflowInstance.class
		};
	private long _workflowInstanceId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _originalTitle;
	private String _status;
	private String _statusCurrentLanguageId;
	private Date _startTime;
	private Date _endTime;
	private long _workflowId;
	private String _workflowUUID;
	private String _screenLogic;
	private long _columnBitmask;
	private WorkflowInstance _escapedModel;
}