/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.kisti.edison.customauthmanager.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.kisti.edison.customauthmanager.service.persistence.UserGroupRoleCustomPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserGroupRoleCustom service. Represents a row in the &quot;EDAUT_UserGroupRoleCustom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.kisti.edison.customauthmanager.model.impl.UserGroupRoleCustomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.kisti.edison.customauthmanager.model.impl.UserGroupRoleCustomImpl}.
 * </p>
 *
 * @author EDISON
 * @see UserGroupRoleCustom
 * @see org.kisti.edison.customauthmanager.model.impl.UserGroupRoleCustomImpl
 * @see org.kisti.edison.customauthmanager.model.impl.UserGroupRoleCustomModelImpl
 * @generated
 */
public interface UserGroupRoleCustomModel extends BaseModel<UserGroupRoleCustom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user group role custom model instance should use the {@link UserGroupRoleCustom} interface instead.
	 */

	/**
	 * Returns the primary key of this user group role custom.
	 *
	 * @return the primary key of this user group role custom
	 */
	public UserGroupRoleCustomPK getPrimaryKey();

	/**
	 * Sets the primary key of this user group role custom.
	 *
	 * @param primaryKey the primary key of this user group role custom
	 */
	public void setPrimaryKey(UserGroupRoleCustomPK primaryKey);

	/**
	 * Returns the user ID of this user group role custom.
	 *
	 * @return the user ID of this user group role custom
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user group role custom.
	 *
	 * @param userId the user ID of this user group role custom
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user group role custom.
	 *
	 * @return the user uuid of this user group role custom
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user group role custom.
	 *
	 * @param userUuid the user uuid of this user group role custom
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the group ID of this user group role custom.
	 *
	 * @return the group ID of this user group role custom
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user group role custom.
	 *
	 * @param groupId the group ID of this user group role custom
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the role ID of this user group role custom.
	 *
	 * @return the role ID of this user group role custom
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this user group role custom.
	 *
	 * @param roleId the role ID of this user group role custom
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the custom ID of this user group role custom.
	 *
	 * @return the custom ID of this user group role custom
	 */
	public long getCustomId();

	/**
	 * Sets the custom ID of this user group role custom.
	 *
	 * @param customId the custom ID of this user group role custom
	 */
	public void setCustomId(long customId);

	/**
	 * Returns the create date of this user group role custom.
	 *
	 * @return the create date of this user group role custom
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this user group role custom.
	 *
	 * @param createDate the create date of this user group role custom
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.kisti.edison.customauthmanager.model.UserGroupRoleCustom userGroupRoleCustom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.kisti.edison.customauthmanager.model.UserGroupRoleCustom> toCacheModel();

	@Override
	public org.kisti.edison.customauthmanager.model.UserGroupRoleCustom toEscapedModel();

	@Override
	public org.kisti.edison.customauthmanager.model.UserGroupRoleCustom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}