/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.kisti.science.platform.app.service.persistence.CommonLibraryPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommonLibrary service. Represents a row in the &quot;ScienceApp_CommonLibrary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.CommonLibraryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.CommonLibraryImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see CommonLibrary
 * @see com.kisti.science.platform.app.model.impl.CommonLibraryImpl
 * @see com.kisti.science.platform.app.model.impl.CommonLibraryModelImpl
 * @generated
 */
public interface CommonLibraryModel extends BaseModel<CommonLibrary>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a common library model instance should use the {@link CommonLibrary} interface instead.
	 */

	/**
	 * Returns the primary key of this common library.
	 *
	 * @return the primary key of this common library
	 */
	public CommonLibraryPK getPrimaryKey();

	/**
	 * Sets the primary key of this common library.
	 *
	 * @param primaryKey the primary key of this common library
	 */
	public void setPrimaryKey(CommonLibraryPK primaryKey);

	/**
	 * Returns the group ID of this common library.
	 *
	 * @return the group ID of this common library
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this common library.
	 *
	 * @param groupId the group ID of this common library
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this common library.
	 *
	 * @return the company ID of this common library
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this common library.
	 *
	 * @param companyId the company ID of this common library
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this common library.
	 *
	 * @return the user ID of this common library
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this common library.
	 *
	 * @param userId the user ID of this common library
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this common library.
	 *
	 * @return the user uuid of this common library
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this common library.
	 *
	 * @param userUuid the user uuid of this common library
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this common library.
	 *
	 * @return the user name of this common library
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this common library.
	 *
	 * @param userName the user name of this common library
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this common library.
	 *
	 * @return the create date of this common library
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this common library.
	 *
	 * @param createDate the create date of this common library
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this common library.
	 *
	 * @return the modified date of this common library
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this common library.
	 *
	 * @param modifiedDate the modified date of this common library
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the lib name of this common library.
	 *
	 * @return the lib name of this common library
	 */
	@AutoEscape
	public String getLibName();

	/**
	 * Sets the lib name of this common library.
	 *
	 * @param libName the lib name of this common library
	 */
	public void setLibName(String libName);

	/**
	 * Returns the c lib ver of this common library.
	 *
	 * @return the c lib ver of this common library
	 */
	@AutoEscape
	public String getCLibVer();

	/**
	 * Sets the c lib ver of this common library.
	 *
	 * @param cLibVer the c lib ver of this common library
	 */
	public void setCLibVer(String cLibVer);

	/**
	 * Returns the sys arch of this common library.
	 *
	 * @return the sys arch of this common library
	 */
	@AutoEscape
	public String getSysArch();

	/**
	 * Sets the sys arch of this common library.
	 *
	 * @param sysArch the sys arch of this common library
	 */
	public void setSysArch(String sysArch);

	/**
	 * Returns the kernel ver of this common library.
	 *
	 * @return the kernel ver of this common library
	 */
	@AutoEscape
	public String getKernelVer();

	/**
	 * Sets the kernel ver of this common library.
	 *
	 * @param kernelVer the kernel ver of this common library
	 */
	public void setKernelVer(String kernelVer);

	/**
	 * Returns the lib path of this common library.
	 *
	 * @return the lib path of this common library
	 */
	@AutoEscape
	public String getLibPath();

	/**
	 * Sets the lib path of this common library.
	 *
	 * @param libPath the lib path of this common library
	 */
	public void setLibPath(String libPath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.CommonLibrary commonLibrary);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.CommonLibrary> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.CommonLibrary toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.CommonLibrary toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}