/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.kisti.science.platform.app.service.persistence.CommonPackagePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommonPackage service. Represents a row in the &quot;ScienceApp_CommonPackage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.CommonPackageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.CommonPackageImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see CommonPackage
 * @see com.kisti.science.platform.app.model.impl.CommonPackageImpl
 * @see com.kisti.science.platform.app.model.impl.CommonPackageModelImpl
 * @generated
 */
public interface CommonPackageModel extends BaseModel<CommonPackage>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a common package model instance should use the {@link CommonPackage} interface instead.
	 */

	/**
	 * Returns the primary key of this common package.
	 *
	 * @return the primary key of this common package
	 */
	public CommonPackagePK getPrimaryKey();

	/**
	 * Sets the primary key of this common package.
	 *
	 * @param primaryKey the primary key of this common package
	 */
	public void setPrimaryKey(CommonPackagePK primaryKey);

	/**
	 * Returns the group ID of this common package.
	 *
	 * @return the group ID of this common package
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this common package.
	 *
	 * @param groupId the group ID of this common package
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this common package.
	 *
	 * @return the company ID of this common package
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this common package.
	 *
	 * @param companyId the company ID of this common package
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this common package.
	 *
	 * @return the user ID of this common package
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this common package.
	 *
	 * @param userId the user ID of this common package
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this common package.
	 *
	 * @return the user uuid of this common package
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this common package.
	 *
	 * @param userUuid the user uuid of this common package
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this common package.
	 *
	 * @return the user name of this common package
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this common package.
	 *
	 * @param userName the user name of this common package
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this common package.
	 *
	 * @return the create date of this common package
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this common package.
	 *
	 * @param createDate the create date of this common package
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this common package.
	 *
	 * @return the modified date of this common package
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this common package.
	 *
	 * @param modifiedDate the modified date of this common package
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the pkg name of this common package.
	 *
	 * @return the pkg name of this common package
	 */
	@AutoEscape
	public String getPkgName();

	/**
	 * Sets the pkg name of this common package.
	 *
	 * @param pkgName the pkg name of this common package
	 */
	public void setPkgName(String pkgName);

	/**
	 * Returns the pkg version of this common package.
	 *
	 * @return the pkg version of this common package
	 */
	@AutoEscape
	public String getPkgVersion();

	/**
	 * Sets the pkg version of this common package.
	 *
	 * @param pkgVersion the pkg version of this common package
	 */
	public void setPkgVersion(String pkgVersion);

	/**
	 * Returns the sys arch of this common package.
	 *
	 * @return the sys arch of this common package
	 */
	@AutoEscape
	public String getSysArch();

	/**
	 * Sets the sys arch of this common package.
	 *
	 * @param sysArch the sys arch of this common package
	 */
	public void setSysArch(String sysArch);

	/**
	 * Returns the install method of this common package.
	 *
	 * @return the install method of this common package
	 */
	@AutoEscape
	public String getInstallMethod();

	/**
	 * Sets the install method of this common package.
	 *
	 * @param installMethod the install method of this common package
	 */
	public void setInstallMethod(String installMethod);

	/**
	 * Returns the install path of this common package.
	 *
	 * @return the install path of this common package
	 */
	@AutoEscape
	public String getInstallPath();

	/**
	 * Sets the install path of this common package.
	 *
	 * @param installPath the install path of this common package
	 */
	public void setInstallPath(String installPath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.CommonPackage commonPackage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.CommonPackage> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.CommonPackage toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.CommonPackage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}