/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortTypeInputdeckUserForm service. Represents a row in the &quot;ScienceApp_PortTypeInputdeckUserForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.PortTypeInputdeckUserFormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.PortTypeInputdeckUserFormImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see PortTypeInputdeckUserForm
 * @see com.kisti.science.platform.app.model.impl.PortTypeInputdeckUserFormImpl
 * @see com.kisti.science.platform.app.model.impl.PortTypeInputdeckUserFormModelImpl
 * @generated
 */
public interface PortTypeInputdeckUserFormModel extends BaseModel<PortTypeInputdeckUserForm> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a port type inputdeck user form model instance should use the {@link PortTypeInputdeckUserForm} interface instead.
	 */

	/**
	 * Returns the primary key of this port type inputdeck user form.
	 *
	 * @return the primary key of this port type inputdeck user form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this port type inputdeck user form.
	 *
	 * @param primaryKey the primary key of this port type inputdeck user form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inputdeck ID of this port type inputdeck user form.
	 *
	 * @return the inputdeck ID of this port type inputdeck user form
	 */
	public long getInputdeckId();

	/**
	 * Sets the inputdeck ID of this port type inputdeck user form.
	 *
	 * @param inputdeckId the inputdeck ID of this port type inputdeck user form
	 */
	public void setInputdeckId(long inputdeckId);

	/**
	 * Returns the port type ID of this port type inputdeck user form.
	 *
	 * @return the port type ID of this port type inputdeck user form
	 */
	public long getPortTypeId();

	/**
	 * Sets the port type ID of this port type inputdeck user form.
	 *
	 * @param portTypeId the port type ID of this port type inputdeck user form
	 */
	public void setPortTypeId(long portTypeId);

	/**
	 * Returns the inputdeck user form of this port type inputdeck user form.
	 *
	 * @return the inputdeck user form of this port type inputdeck user form
	 */
	@AutoEscape
	public String getInputdeckUserForm();

	/**
	 * Sets the inputdeck user form of this port type inputdeck user form.
	 *
	 * @param inputdeckUserForm the inputdeck user form of this port type inputdeck user form
	 */
	public void setInputdeckUserForm(String inputdeckUserForm);

	/**
	 * Returns the user ID of this port type inputdeck user form.
	 *
	 * @return the user ID of this port type inputdeck user form
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this port type inputdeck user form.
	 *
	 * @param userId the user ID of this port type inputdeck user form
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this port type inputdeck user form.
	 *
	 * @return the user uuid of this port type inputdeck user form
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this port type inputdeck user form.
	 *
	 * @param userUuid the user uuid of this port type inputdeck user form
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this port type inputdeck user form.
	 *
	 * @return the user name of this port type inputdeck user form
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this port type inputdeck user form.
	 *
	 * @param userName the user name of this port type inputdeck user form
	 */
	public void setUserName(String userName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.PortTypeInputdeckUserForm portTypeInputdeckUserForm);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.PortTypeInputdeckUserForm> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeInputdeckUserForm toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeInputdeckUserForm toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}