/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortTypeEditorLink service. Represents a row in the &quot;ScienceApp_PortTypeEditorLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.PortTypeEditorLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.PortTypeEditorLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see PortTypeEditorLink
 * @see com.kisti.science.platform.app.model.impl.PortTypeEditorLinkImpl
 * @see com.kisti.science.platform.app.model.impl.PortTypeEditorLinkModelImpl
 * @generated
 */
public interface PortTypeEditorLinkModel extends BaseModel<PortTypeEditorLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a port type editor link model instance should use the {@link PortTypeEditorLink} interface instead.
	 */

	/**
	 * Returns the primary key of this port type editor link.
	 *
	 * @return the primary key of this port type editor link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this port type editor link.
	 *
	 * @param primaryKey the primary key of this port type editor link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this port type editor link.
	 *
	 * @return the uuid of this port type editor link
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this port type editor link.
	 *
	 * @param uuid the uuid of this port type editor link
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the port type editor link ID of this port type editor link.
	 *
	 * @return the port type editor link ID of this port type editor link
	 */
	public long getPortTypeEditorLinkId();

	/**
	 * Sets the port type editor link ID of this port type editor link.
	 *
	 * @param portTypeEditorLinkId the port type editor link ID of this port type editor link
	 */
	public void setPortTypeEditorLinkId(long portTypeEditorLinkId);

	/**
	 * Returns the company ID of this port type editor link.
	 *
	 * @return the company ID of this port type editor link
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this port type editor link.
	 *
	 * @param companyId the company ID of this port type editor link
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the port type ID of this port type editor link.
	 *
	 * @return the port type ID of this port type editor link
	 */
	public long getPortTypeId();

	/**
	 * Sets the port type ID of this port type editor link.
	 *
	 * @param portTypeId the port type ID of this port type editor link
	 */
	public void setPortTypeId(long portTypeId);

	/**
	 * Returns the editor ID of this port type editor link.
	 *
	 * @return the editor ID of this port type editor link
	 */
	public long getEditorId();

	/**
	 * Sets the editor ID of this port type editor link.
	 *
	 * @param editorId the editor ID of this port type editor link
	 */
	public void setEditorId(long editorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.PortTypeEditorLink portTypeEditorLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.PortTypeEditorLink> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeEditorLink toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeEditorLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}