/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PortType service. Represents a row in the &quot;ScienceApp_PortType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.PortTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.PortTypeImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see PortType
 * @see com.kisti.science.platform.app.model.impl.PortTypeImpl
 * @see com.kisti.science.platform.app.model.impl.PortTypeModelImpl
 * @generated
 */
public interface PortTypeModel extends BaseModel<PortType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a port type model instance should use the {@link PortType} interface instead.
	 */

	/**
	 * Returns the primary key of this port type.
	 *
	 * @return the primary key of this port type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this port type.
	 *
	 * @param primaryKey the primary key of this port type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this port type.
	 *
	 * @return the uuid of this port type
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this port type.
	 *
	 * @param uuid the uuid of this port type
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the port type ID of this port type.
	 *
	 * @return the port type ID of this port type
	 */
	public long getPortTypeId();

	/**
	 * Sets the port type ID of this port type.
	 *
	 * @param portTypeId the port type ID of this port type
	 */
	public void setPortTypeId(long portTypeId);

	/**
	 * Returns the company ID of this port type.
	 *
	 * @return the company ID of this port type
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this port type.
	 *
	 * @param companyId the company ID of this port type
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this port type.
	 *
	 * @return the user ID of this port type
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this port type.
	 *
	 * @param userId the user ID of this port type
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this port type.
	 *
	 * @return the user uuid of this port type
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this port type.
	 *
	 * @param userUuid the user uuid of this port type
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this port type.
	 *
	 * @return the create date of this port type
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this port type.
	 *
	 * @param createDate the create date of this port type
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the default editor ID of this port type.
	 *
	 * @return the default editor ID of this port type
	 */
	public long getDefaultEditorId();

	/**
	 * Sets the default editor ID of this port type.
	 *
	 * @param defaultEditorId the default editor ID of this port type
	 */
	public void setDefaultEditorId(long defaultEditorId);

	/**
	 * Returns the default analyzer ID of this port type.
	 *
	 * @return the default analyzer ID of this port type
	 */
	public long getDefaultAnalyzerId();

	/**
	 * Sets the default analyzer ID of this port type.
	 *
	 * @param defaultAnalyzerId the default analyzer ID of this port type
	 */
	public void setDefaultAnalyzerId(long defaultAnalyzerId);

	/**
	 * Returns the name of this port type.
	 *
	 * @return the name of this port type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this port type.
	 *
	 * @param name the name of this port type
	 */
	public void setName(String name);

	/**
	 * Returns the data type of this port type.
	 *
	 * @return the data type of this port type
	 */
	@AutoEscape
	public String getDataType();

	/**
	 * Sets the data type of this port type.
	 *
	 * @param dataType the data type of this port type
	 */
	public void setDataType(String dataType);

	/**
	 * Returns the sample file path of this port type.
	 *
	 * @return the sample file path of this port type
	 */
	@AutoEscape
	public String getSampleFilePath();

	/**
	 * Sets the sample file path of this port type.
	 *
	 * @param sampleFilePath the sample file path of this port type
	 */
	public void setSampleFilePath(String sampleFilePath);

	/**
	 * Returns the target language of this port type.
	 *
	 * @return the target language of this port type
	 */
	@AutoEscape
	public String getTargetLanguage();

	/**
	 * Sets the target language of this port type.
	 *
	 * @param targetLanguage the target language of this port type
	 */
	public void setTargetLanguage(String targetLanguage);

	/**
	 * Returns the status of this port type.
	 *
	 * @return the status of this port type
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this port type.
	 *
	 * @param status the status of this port type
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.kisti.science.platform.app.model.PortType portType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.PortType> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.PortType toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.PortType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}