/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortTypeInputdeckForm service. Represents a row in the &quot;ScienceApp_PortTypeInputdeckForm&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.PortTypeInputdeckFormModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.PortTypeInputdeckFormImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see PortTypeInputdeckForm
 * @see com.kisti.science.platform.app.model.impl.PortTypeInputdeckFormImpl
 * @see com.kisti.science.platform.app.model.impl.PortTypeInputdeckFormModelImpl
 * @generated
 */
public interface PortTypeInputdeckFormModel extends BaseModel<PortTypeInputdeckForm> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a port type inputdeck form model instance should use the {@link PortTypeInputdeckForm} interface instead.
	 */

	/**
	 * Returns the primary key of this port type inputdeck form.
	 *
	 * @return the primary key of this port type inputdeck form
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this port type inputdeck form.
	 *
	 * @param primaryKey the primary key of this port type inputdeck form
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the port type ID of this port type inputdeck form.
	 *
	 * @return the port type ID of this port type inputdeck form
	 */
	public long getPortTypeId();

	/**
	 * Sets the port type ID of this port type inputdeck form.
	 *
	 * @param portTypeId the port type ID of this port type inputdeck form
	 */
	public void setPortTypeId(long portTypeId);

	/**
	 * Returns the inputdeck form of this port type inputdeck form.
	 *
	 * @return the inputdeck form of this port type inputdeck form
	 */
	@AutoEscape
	public String getInputdeckForm();

	/**
	 * Sets the inputdeck form of this port type inputdeck form.
	 *
	 * @param inputdeckForm the inputdeck form of this port type inputdeck form
	 */
	public void setInputdeckForm(String inputdeckForm);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.PortTypeInputdeckForm portTypeInputdeckForm);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.PortTypeInputdeckForm> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeInputdeckForm toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.PortTypeInputdeckForm toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}