/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ScienceAppCategoryLink service. Represents a row in the &quot;ScienceApp_ScienceAppCategoryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.ScienceAppCategoryLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.ScienceAppCategoryLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see ScienceAppCategoryLink
 * @see com.kisti.science.platform.app.model.impl.ScienceAppCategoryLinkImpl
 * @see com.kisti.science.platform.app.model.impl.ScienceAppCategoryLinkModelImpl
 * @generated
 */
public interface ScienceAppCategoryLinkModel extends BaseModel<ScienceAppCategoryLink>,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app category link model instance should use the {@link ScienceAppCategoryLink} interface instead.
	 */

	/**
	 * Returns the primary key of this science app category link.
	 *
	 * @return the primary key of this science app category link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this science app category link.
	 *
	 * @param primaryKey the primary key of this science app category link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this science app category link.
	 *
	 * @return the uuid of this science app category link
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this science app category link.
	 *
	 * @param uuid the uuid of this science app category link
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the science app category link ID of this science app category link.
	 *
	 * @return the science app category link ID of this science app category link
	 */
	public long getScienceAppCategoryLinkId();

	/**
	 * Sets the science app category link ID of this science app category link.
	 *
	 * @param scienceAppCategoryLinkId the science app category link ID of this science app category link
	 */
	public void setScienceAppCategoryLinkId(long scienceAppCategoryLinkId);

	/**
	 * Returns the group ID of this science app category link.
	 *
	 * @return the group ID of this science app category link
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this science app category link.
	 *
	 * @param groupId the group ID of this science app category link
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this science app category link.
	 *
	 * @return the company ID of this science app category link
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this science app category link.
	 *
	 * @param companyId the company ID of this science app category link
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this science app category link.
	 *
	 * @return the user ID of this science app category link
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this science app category link.
	 *
	 * @param userId the user ID of this science app category link
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this science app category link.
	 *
	 * @return the user uuid of this science app category link
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this science app category link.
	 *
	 * @param userUuid the user uuid of this science app category link
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this science app category link.
	 *
	 * @return the create date of this science app category link
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this science app category link.
	 *
	 * @param createDate the create date of this science app category link
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this science app category link.
	 *
	 * @return the modified date of this science app category link
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this science app category link.
	 *
	 * @param modifiedDate the modified date of this science app category link
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this science app category link.
	 *
	 * @return the category ID of this science app category link
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this science app category link.
	 *
	 * @param categoryId the category ID of this science app category link
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the science app ID of this science app category link.
	 *
	 * @return the science app ID of this science app category link
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app category link.
	 *
	 * @param scienceAppId the science app ID of this science app category link
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the parent category ID of this science app category link.
	 *
	 * @return the parent category ID of this science app category link
	 */
	public long getParentCategoryId();

	/**
	 * Sets the parent category ID of this science app category link.
	 *
	 * @param parentCategoryId the parent category ID of this science app category link
	 */
	public void setParentCategoryId(long parentCategoryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.ScienceAppCategoryLink scienceAppCategoryLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.ScienceAppCategoryLink> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.ScienceAppCategoryLink toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.ScienceAppCategoryLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}