/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.science.platform.app.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ScienceAppManager service. Represents a row in the &quot;ScienceApp_ScienceAppManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.science.platform.app.model.impl.ScienceAppManagerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.science.platform.app.model.impl.ScienceAppManagerImpl}.
 * </p>
 *
 * @author Jerry H. Seo & Young Suh
 * @see ScienceAppManager
 * @see com.kisti.science.platform.app.model.impl.ScienceAppManagerImpl
 * @see com.kisti.science.platform.app.model.impl.ScienceAppManagerModelImpl
 * @generated
 */
public interface ScienceAppManagerModel extends BaseModel<ScienceAppManager> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a science app manager model instance should use the {@link ScienceAppManager} interface instead.
	 */

	/**
	 * Returns the primary key of this science app manager.
	 *
	 * @return the primary key of this science app manager
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this science app manager.
	 *
	 * @param primaryKey the primary key of this science app manager
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the science app manager ID of this science app manager.
	 *
	 * @return the science app manager ID of this science app manager
	 */
	public long getScienceAppManagerId();

	/**
	 * Sets the science app manager ID of this science app manager.
	 *
	 * @param scienceAppManagerId the science app manager ID of this science app manager
	 */
	public void setScienceAppManagerId(long scienceAppManagerId);

	/**
	 * Returns the user ID of this science app manager.
	 *
	 * @return the user ID of this science app manager
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this science app manager.
	 *
	 * @param userId the user ID of this science app manager
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this science app manager.
	 *
	 * @return the user uuid of this science app manager
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this science app manager.
	 *
	 * @param userUuid the user uuid of this science app manager
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this science app manager.
	 *
	 * @return the create date of this science app manager
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this science app manager.
	 *
	 * @param createDate the create date of this science app manager
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the science app ID of this science app manager.
	 *
	 * @return the science app ID of this science app manager
	 */
	public long getScienceAppId();

	/**
	 * Sets the science app ID of this science app manager.
	 *
	 * @param scienceAppId the science app ID of this science app manager
	 */
	public void setScienceAppId(long scienceAppId);

	/**
	 * Returns the manager ID of this science app manager.
	 *
	 * @return the manager ID of this science app manager
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this science app manager.
	 *
	 * @param managerId the manager ID of this science app manager
	 */
	public void setManagerId(long managerId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.kisti.science.platform.app.model.ScienceAppManager scienceAppManager);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.kisti.science.platform.app.model.ScienceAppManager> toCacheModel();

	@Override
	public com.kisti.science.platform.app.model.ScienceAppManager toEscapedModel();

	@Override
	public com.kisti.science.platform.app.model.ScienceAppManager toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}